params:
  seed: 42

  env:
    clip_observations: 5.0
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [1024, 512, 256, 128, 64]
      activation: gelu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: BR_UR5e_FF
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.008
    score_to_win: 100000000
    max_epochs: 1000
    save_best_after: 10
    save_frequency: 500
    grad_norm: 1.0
    entropy_coef: 0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 64 #192/4=
    minibatch_size: 32768
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    seq_length: 64
    bounds_loss_coef: 0.0001
    
        
    central_value_config:
      minibatch_size: 32768 # 32768/2 = 16384 -- 32768*2 = 65536
      mini_epochs: 5
      learning_rate: 5e-4
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.008
      clip_value: True
      normalize_input: True
      truncate_grads: True
      value_bootstrap: True

      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [1024, 512, 256, 128, 64]
          activation: gelu
          d2rl: False
          initializer:
            name: default
          regularizer:
            name: None